# Generated by Django 5.0.7 on 2024-08-04 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
